import { SlabStock, CustomerQuery, Announcement, TrashItem } from '../types';

export const COMPANY_DETAILS = {
  name: 'SRI BALAJI GRANITES & MARBLES',
  tagline: 'We Have Granite & Marble, Black Stone, Wall Tiles, Floor Tiles & Marble Sinks Available',
  phonePrimary: '9828400811',
  phoneSecondary: '9982749180',
  address: 'Site No. 17, 18 & 19, Sir M. Vishveshwaraiah Extension, Southern Side Of CSI Hospital, Bengaluru Rural District - 562114',
  factoryAddress: 'Sri Balaji Granites & Factory, Chittoor',
  exportAddress: 'Suguna Export, Vishakapatnam',
  googleMapsUrl: 'https://maps.google.com/?q=Bengaluru+Rural',
};

export const GODOWN_INFO = [
  { id: 'godown_1', name: 'Bangalore Yard', managerName: 'Sales & Yard Desk', location: 'Site No. 17-19, Bengaluru Rural' },
  { id: 'godown_2', name: 'Chittoor Factory', managerName: 'Factory Dispatch', location: 'Chittoor Unit' },
  { id: 'godown_3', name: 'Vishakapatnam Export', managerName: 'Export Counter', location: 'Suguna Export, Visakhapatnam' },
];

export const INITIAL_SLABS: SlabStock[] = [
  {
    id: 'slab-01',
    godownId: 'godown_1',
    godownName: 'Bangalore Yard',
    blockNumber: 'SBG-SLV-101',
    title: 'Silver Waves Premium Granite',
    category: 'Granite',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    length: 10.5,
    width: 6.2,
    unit: 'feet',
    pieces: 38,
    totalSqFt: 2473,
    totalSqMeters: 229.7,
    thicknessMm: 18,
    finish: 'Polished',
    pricePerSqFt: 140,
    isSold: false,
    lotName: 'Silver Wave Heavy Stack',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'slab-02',
    godownId: 'godown_1',
    godownName: 'Bangalore Yard',
    blockNumber: 'SBG-BLK-204',
    title: 'Lapotra Black Pearl Granite',
    category: 'Granite',
    imageUrl: 'https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&w=1200&q=80',
    length: 11.0,
    width: 6.5,
    unit: 'feet',
    pieces: 42,
    totalSqFt: 3003,
    totalSqMeters: 279,
    thicknessMm: 20,
    finish: 'Lappato',
    pricePerSqFt: 185,
    isSold: false,
    lotName: 'Lapotra Black Leathered Lot',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'slab-03',
    godownId: 'godown_2',
    godownName: 'Chittoor Factory',
    blockNumber: 'SBG-STL-309',
    title: 'Steel Grey Polished Granite',
    category: 'Granite',
    imageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b7?auto=format&fit=crop&w=1200&q=80',
    length: 9.8,
    width: 5.8,
    unit: 'feet',
    pieces: 50,
    totalSqFt: 2842,
    totalSqMeters: 264,
    thicknessMm: 18,
    finish: 'Polished',
    pricePerSqFt: 115,
    isSold: false,
    lotName: 'Steel Grey Fine Grain',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'slab-04',
    godownId: 'godown_1',
    godownName: 'Bangalore Yard',
    blockNumber: 'SBG-WHT-881',
    title: 'Kashmir White Granite',
    category: 'Granite',
    imageUrl: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1200&q=80',
    length: 10.2,
    width: 6.0,
    unit: 'feet',
    pieces: 32,
    totalSqFt: 1958,
    totalSqMeters: 182,
    thicknessMm: 18,
    finish: 'Polished',
    pricePerSqFt: 160,
    isSold: false,
    lotName: 'White Galaxy Spotted Lot',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'slab-05',
    godownId: 'godown_2',
    godownName: 'Chittoor Factory',
    blockNumber: 'SBG-PNK-502',
    title: 'Rosy Pink Classic Granite',
    category: 'Granite',
    imageUrl: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80',
    length: 8.8,
    width: 5.2,
    unit: 'feet',
    pieces: 45,
    totalSqFt: 2059,
    totalSqMeters: 191,
    thicknessMm: 18,
    finish: 'Polished',
    pricePerSqFt: 95,
    isSold: false,
    lotName: 'South Rosy Pink Lot',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'slab-06',
    godownId: 'godown_3',
    godownName: 'Vishakapatnam Export',
    blockNumber: 'SBG-TAN-405',
    title: 'Tan Brown Heavy Granite Slab',
    category: 'Granite',
    imageUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80',
    length: 10.8,
    width: 6.4,
    unit: 'feet',
    pieces: 28,
    totalSqFt: 1935,
    totalSqMeters: 180,
    thicknessMm: 20,
    finish: 'Polished',
    pricePerSqFt: 135,
    isSold: false,
    lotName: 'Coffee Tan Brown',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'slab-07',
    godownId: 'godown_1',
    godownName: 'Bangalore Yard',
    blockNumber: 'SBG-JBLK-901',
    title: 'Absolute Jet Black Granite',
    category: 'Granite',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80',
    length: 11.2,
    width: 6.8,
    unit: 'feet',
    pieces: 25,
    totalSqFt: 1904,
    totalSqMeters: 177,
    thicknessMm: 20,
    finish: 'Polished',
    pricePerSqFt: 210,
    isSold: false,
    lotName: 'Premium Jet Black Mirror Finish',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'slab-08',
    godownId: 'godown_3',
    godownName: 'Vishakapatnam Export',
    blockNumber: 'SBG-SNK-12',
    title: 'Handcrafted Marble Sink & Vessel',
    category: 'Indian Marble',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80',
    length: 2.0,
    width: 1.5,
    unit: 'feet',
    pieces: 15,
    totalSqFt: 45,
    totalSqMeters: 4.2,
    thicknessMm: 25,
    finish: 'Honed',
    pricePerSqFt: 350,
    isSold: false,
    lotName: 'Carved Sink & Wall Tiles',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'slab-09',
    godownId: 'godown_1',
    godownName: 'Bangalore Yard',
    blockNumber: 'SBG-ITM-701',
    title: 'Italian Bottochino Cream Marble',
    category: 'Italian Marble',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    length: 9.5,
    width: 5.5,
    unit: 'feet',
    pieces: 30,
    totalSqFt: 1567,
    totalSqMeters: 145.5,
    thicknessMm: 18,
    finish: 'Polished',
    pricePerSqFt: 260,
    isSold: false,
    lotName: 'Royal Italian Bottochino',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'slab-10',
    godownId: 'godown_3',
    godownName: 'Vishakapatnam Export',
    blockNumber: 'SBG-TLE-602',
    title: 'Polished Wall & Floor Tiles Lot',
    category: 'Sandstone',
    imageUrl: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1200&q=80',
    length: 4.0,
    width: 2.0,
    unit: 'feet',
    pieces: 120,
    totalSqFt: 960,
    totalSqMeters: 89.1,
    thicknessMm: 12,
    finish: 'Polished',
    pricePerSqFt: 65,
    isSold: false,
    lotName: 'Vitified & Stone Wall Tiles',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'slab-11',
    godownId: 'godown_2',
    godownName: 'Chittoor Factory',
    blockNumber: 'SBG-MKT-303',
    title: 'Makrana Pure White Marble',
    category: 'Indian Marble',
    imageUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80',
    length: 8.5,
    width: 5.2,
    unit: 'feet',
    pieces: 40,
    totalSqFt: 1768,
    totalSqMeters: 164.2,
    thicknessMm: 16,
    finish: 'Polished',
    pricePerSqFt: 320,
    isSold: false,
    lotName: 'Makrana White Pristine Lot',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'slab-12',
    godownId: 'godown_1',
    godownName: 'Bangalore Yard',
    blockNumber: 'SBG-ONY-404',
    title: 'Translucent Backlit Honey Onyx',
    category: 'Onyx',
    imageUrl: 'https://images.unsplash.com/photo-1518640467707-6811f4a6ab73?auto=format&fit=crop&w=1200&q=80',
    length: 7.5,
    width: 4.5,
    unit: 'feet',
    pieces: 12,
    totalSqFt: 405,
    totalSqMeters: 37.6,
    thicknessMm: 16,
    finish: 'Polished',
    pricePerSqFt: 620,
    isSold: false,
    lotName: 'Honey Onyx Backlit Special',
    createdAt: new Date().toISOString(),
  }
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-01',
    title: '👑 Sri Balaji Granites & Marbles - Bangalore • Chittoor • Vishakapatnam',
    message: 'Welcome to Sri Balaji Granites & Marbles! Direct quarry rates on Granite, Marble, Wall/Floor Tiles & Marble Sinks. Call 9828400811 or 9982749180.',
    isActive: true,
    date: new Date().toISOString().split('T')[0],
    type: 'offer',
  },
  {
    id: 'ann-02',
    title: '✨ Fresh Slab Arrival at Bangalore Yard & Chittoor Factory',
    message: 'Over 20,000 Sq.Ft of Silver Waves, Lapotra Black, Absolute Black & Steel Grey Granites freshly arrived at Bangalore & Chittoor yards!',
    isActive: true,
    date: new Date().toISOString().split('T')[0],
    type: 'arrival',
  },
];

export const INITIAL_QUERIES: CustomerQuery[] = [
  {
    id: 'query-101',
    orderNumber: 'ORD-2026-8801',
    clientName: 'Rajesh Sharma',
    mobileNumber: '9829012345',
    deliveryAddress: 'Plot 42, Civil Lines, Jaipur',
    preferredGodown: 'godown_1',
    requirement: 'Villa Living Room Flooring (Need high gloss white finish marble)',
    dimensionUnit: 'feet',
    requestedQuantitySqFt: 1800,
    selectedSlabs: [INITIAL_SLABS[1], INITIAL_SLABS[6]],
    totalEstimatedCost: 630000,
    status: 'Quoted',
    createdAt: '2026-07-29T10:30:00.000Z',
    notes: 'Quoted @ Rs 350/sq.ft. Sent samples via courier.',
  },
  {
    id: 'query-102',
    orderNumber: 'ORD-2026-8802',
    clientName: 'Sunita Patel (Interior Designer)',
    mobileNumber: '9898011223',
    deliveryAddress: 'SG Highway, Ahmedabad',
    preferredGodown: 'godown_3',
    requirement: 'Kitchen Countertop & Backlit Bar Table Onyx',
    dimensionUnit: 'meters',
    requestedQuantitySqFt: 600,
    selectedSlabs: [INITIAL_SLABS[3], INITIAL_SLABS[4]],
    totalEstimatedCost: 390000,
    status: 'Pending',
    createdAt: '2026-07-30T06:15:00.000Z',
    notes: 'Requested WhatsApp quotation with shipping details.',
  },
];

export const INITIAL_TRASH: TrashItem[] = [
  {
    id: 'trash-99',
    slab: {
      id: 'slab-old-01',
      godownId: 'godown_1',
      godownName: 'Bangalore Yard',
      blockNumber: 'OLD-KAT-11',
      title: 'Katni Beige Marble Slab',
      category: 'Indian Marble',
      imageUrl: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=800&q=80',
      length: 200,
      width: 120,
      unit: 'centimeters',
      pieces: 10,
      totalSqFt: 258,
      totalSqMeters: 24,
      thicknessMm: 16,
      finish: 'Polished',
      pricePerSqFt: 95,
      isSold: false,
      createdAt: '2026-07-20T00:00:00.000Z',
    },
    deletedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    deletedBy: 'Manager Bangalore',
    expiresAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
  }
];

